### ISSUE TITLE
Unicode string encoding issue? 

### ISSUE THREAD

**Issue by mars-lan** [Kudo/react-native-v8#14]
Encountered the following encoding issue when using 0.60.4-patch.1 + RN 0.60.4. The same string displayed perfectly on JSC or Hermes.

<img width="403" alt="Screen Shot 2019-08-27 at 8 07 44 PM" src="https://user-images.githubusercontent.com/24240669/63822957-f17d0580-c906-11e9-9a23-24056bbe9c3a.png">

**Comment by Kudo** [comment]
That is duplicated of #13 and I am also curious of the root cause.

Could you please these information? Thank you for reporting this issue to me.

1. Is the problem reproducible on Android emulator or only on real device?

2. What's your Android system language?

3. What's is your react-native version and react-native-v8 version? Please check the real version from yarn.lock.

4. On the same device which had the problem, could you reproduce the problem for a simple test case?
E.g. react-native init RN059 --version react-native@^0.59.10, adding react-native-v8 and use my sample code above.

5. Verify the text from bundle, is the text a normal UTF-8 text? (Download bundle from wget 'http://localhost:8081/index.bundle?platform=android&dev=true&minify=false')

**Comment by Kudo** [comment]
Publish react-native-v8 `0.59.10-patch.2`, `0.60.4-patch.2`, `0.60.5-patch.0` which all include #17 fix.
Please choose a version to see if the new version did help for the issue.
Thanks for all your help.
