### ISSUE TITLE
How do I compile this project myself？

### ISSUE THREAD

**Issue by hanhailong** [Kudo/react-native-v8#69]
How do I compile this project myself？

**Comment by Gutyn** [comment]
## v8 with RN forked.
- [ ] `git clone https://github.com/YourRepos/react-native.git`
- [ ] cd into `react-native`
- [ ] `git checkout <branch>` where branch is the name of the branch you're trying to compile
- [ ] `git clone git@github.com:YourRepo/react-native-v8.git`
- [ ] cd into `react-native-v8`
- [ ] make sure `scripts/build.sh` points to our fork rather than facebook repo.
- [ ] `yarn install`
- [ ] run `export RN_VERSION='0.63.4-myrepo'` (or whatever your RN branch is)
- [ ] ```rm -rf build && rm -rf dist.tgz && rm -rf dis && scripts/build.sh && tar cvfz dist.tgz dist```
- [ ] change the repo version to the needed one in `package.json`
- [ ] `npm pack`
- [ ] publish it to gemfury or others.



*Troubleshooting:*
- [ ] _Problem:_

You run the react-native-v8 build script and one of the patches fails to apply. 

_Solution:_

Check the value of `$RN_VERSION` and the version of react-native-v8 you have installed. There are different patches included in the react-native-v8 repo for different versions of React Native, and you need to ensure that you are applying the correct patches to the correct version of RN. If you are updating React Native, you will also need to merge the correct version of the code from https://github.com/Kudo/react-native-v8 into our fork.
- [ ] _Problem_
> Task :ReactAndroid:androidJavadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:androidJavadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/YourName/Documents/workspace/react-native-v8/build/ReactAndroid/build/tmp/androidJavadoc/javadoc.options'
_solution_
Make sure you have `$JAVA_HOME` set (jdk).
